export const HOME_DETAIL_SET_LOADING = '@HOME_DETAIL/SET_LOADING';
export const HOME_DETAIL_ADD_OPERATION = '@HOME_DETAIL/ADD_OPERATION';
export const HOME_DETAIL_SET_ERROR = '@HOME_DETAIL/SET_ERROR';
